[package]
name = "guide"
version = "0.1.0"
authors = ["Amin Abdisamad <amin.abdisamad@b4finance.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "guide"
path = "main.rs"
